<?php

namespace Database\Seeders\Junta;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Junta\Teacher;

class TeacherSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {


      $seeds = [
        [ 'name'=> "ROMINA DEL CARMEN", 'lastname'=> "ZALAZAR LOPEZ", 'dni'=> "35023754" ],
        [ 'name'=> "GABRIELA BELEN", 'lastname'=> "CASTILLO", 'dni'=> "35735859" ],
        [ 'name'=> "AGOSTINA SOFIA", 'lastname'=> "QUEVEDO DIAZ", 'dni'=> "43058116" ],
        [ 'name'=> "ANA BEATRIZ", 'lastname'=> "ORREGO", 'dni'=> "31276659" ],
        [ 'name'=> "CAMILA MILAGROS", 'lastname'=> "GONZALES ESPINOZA", 'dni'=> "43689388" ],
        [ 'name'=> "CECILIA ENRIQUETA", 'lastname'=> "ARGUELLO", 'dni'=> "36864662" ],
        [ 'name'=> "CINTHIA GIMENA", 'lastname'=> "ESPEJO RODRIGUEZ", 'dni'=> "34788785" ],
        [ 'name'=> "DANIELA GEORGINA", 'lastname'=> "CARMONA", 'dni'=> "32007674" ],
        [ 'name'=> "DAYANA INÉS", 'lastname'=> "PAEZ CASTRO", 'dni'=> "44126950" ],
        [ 'name'=> "SOFÍA GUADALUPE", 'lastname'=> "GONZALEZ RODRIGUEZ", 'dni'=> "43157592" ],
        [ 'name'=> "VERONICA", 'lastname'=> "SARMIENTO GONZALEZ", 'dni'=> "41830653" ],
        [ 'name'=> "VICTORIA SOLEDAD", 'lastname'=> "GONZALEZ ROQUE", 'dni'=> "42452469" ],
        [ 'name'=> "GONZALO GABRIEL", 'lastname'=> "VARGAS-MAZZITELLI", 'dni'=> "39995840" ],
        [ 'name'=> "JANET ELIANA", 'lastname'=> "PERCHET", 'dni'=> "38463014" ],
        [ 'name'=> "JENNIFER ARIANA", 'lastname'=> "CASTRO", 'dni'=> "43688787" ],
        [ 'name'=> "JESICA GISELA", 'lastname'=> "LUNA MARRELLI", 'dni'=> "32376444" ],
        [ 'name'=> "JOHANA PAOLA", 'lastname'=> "STORNIOLO", 'dni'=> "34698563" ],
        [ 'name'=> "LEANDRO GABRIEL", 'lastname'=> "GORDILLO", 'dni'=> "42130943" ],
        [ 'name'=> "LILIAN YASMIN", 'lastname'=> "TELLO", 'dni'=> "39996076" ],
        [ 'name'=> "MARIA BELEN", 'lastname'=> "SCHEFFER", 'dni'=> "35506885" ],
        [ 'name'=> "MARIANELA", 'lastname'=> "AGÜERO", 'dni'=> "40592380" ],
        [ 'name'=> "MARISOL DEL VALLE", 'lastname'=> "VIDELA", 'dni'=> "41830780" ],
        [ 'name'=> "MELISA AYELEN", 'lastname'=> "SALINAS PIZARRO", 'dni'=> "40591911" ],
        [ 'name'=> "MELISA GABRIELA", 'lastname'=> "RODRIGUEZ", 'dni'=> "38460451" ],
        [ 'name'=> "MILAGROS MARÍA PÍA", 'lastname'=> "FONZALIDA", 'dni'=> "45635161" ],
        [ 'name'=> "NESTOR JESUS", 'lastname'=> "ARIZA", 'dni'=> "39956020" ],
        [ 'name'=> "ABRIL MOIRA DEOLINDA", 'lastname'=> "PÉREZ ALANIZ", 'dni'=> "39524172" ],
        [ 'name'=> "ADRIANA", 'lastname'=> "FACCIO", 'dni'=> "29481488" ],
        [ 'name'=> "ADRIANA AZUCENA", 'lastname'=> "ANDRADA OCHOA", 'dni'=> "43555652" ],
        [ 'name'=> "ADRIANA MICAELA", 'lastname'=> "ROJA ALFARO", 'dni'=> "37507258" ],
        [ 'name'=> "AGOSTINA BELEN", 'lastname'=> "RIOS GUEVARA", 'dni'=> "42452160" ],
        [ 'name'=> "AGOSTINA DENIS", 'lastname'=> "ADARO GARCIA", 'dni'=> "36033587" ],
        [ 'name'=> "AGOSTINA GUADALUPE", 'lastname'=> "RUIZ PUCHETTA", 'dni'=> "42516928" ],
        [ 'name'=> "AGUSTIN", 'lastname'=> "SASSO", 'dni'=> "4082424" ],
        [ 'name'=> "AGUSTIN ABELARDO", 'lastname'=> "PAREDES VEDIA", 'dni'=> "43642603" ],
        [ 'name'=> "AGUSTIN EZEQUIEL", 'lastname'=> "LUNA AHUMADA", 'dni'=> "44665711" ],
        [ 'name'=> "AGUSTIN GENARO", 'lastname'=> "MARQUEZ BILBAO", 'dni'=> "42744213" ],
        [ 'name'=> "AGUSTINA", 'lastname'=> "OTANE", 'dni'=> "41270854" ],
        [ 'name'=> "AGUSTINA BELEN", 'lastname'=> "BECERRA CATALDO", 'dni'=> "39414449" ],
        [ 'name'=> "AGUSTINA FERNANDA", 'lastname'=> "CASTRO", 'dni'=> "41643906" ],
        [ 'name'=> "AGUSTINA NAHIR", 'lastname'=> "AUBONE CORTS", 'dni'=> "37531387" ],
        [ 'name'=> "AGUSTINA PAOLA", 'lastname'=> "PACHECO", 'dni'=> "40470088" ],
        [ 'name'=> "AIMARA VALENTINA", 'lastname'=> "QUIROGA MARTINEZ", 'dni'=> "43339789" ],
        [ 'name'=> "ALAN GABRIEL", 'lastname'=> "AGUILERA", 'dni'=> "37203392" ],
        [ 'name'=> "ALDANA BELÉN", 'lastname'=> "AGUILERA", 'dni'=> "43849727" ],
        [ 'name'=> "ALDANA CECILIA", 'lastname'=> "DONCEL", 'dni'=> "38217316" ],
        [ 'name'=> "ALDANA MILAGROS", 'lastname'=> "BERENGUER DAVILA", 'dni'=> "44060930" ],
        [ 'name'=> "ALEGANDRA MARCELA", 'lastname'=> "ELIZONDO", 'dni'=> "33321947" ],
        [ 'name'=> "ALEJANDRA ANAHI", 'lastname'=> "CHIRINO VALDEZ", 'dni'=> "42990769" ],
        [
          'name'=> "ALEJANDRA DEL VALLE",
          'lastname'=> "GONZÁLEZ FERNÁNDEZ",
          'dni'=> "32718687",
        ],
        [
          'name'=> "ALEJANDRO NICOLAS",
          'lastname'=> "OLIVARES TOEDTMANN",
          'dni'=> "40470698",
        ],
        [ 'name'=> "ALESANDRO JULIO", 'lastname'=> "CABALLERO NARVAEZ", 'dni'=> "35923544" ],
        [ 'name'=> "ALESSANDRA", 'lastname'=> "DEGIORGIS DE LA TORRE", 'dni'=> "48693768" ],
        [ 'name'=> "ALEXANDER RAMON", 'lastname'=> "ZAMORA", 'dni'=> "39376645" ],
        [ 'name'=> "ALEXIS AGUSTIN", 'lastname'=> "SILLERO TABARELLI", 'dni'=> "41958270" ],
        [ 'name'=> "ALICIA VERONICA", 'lastname'=> "MARINERO", 'dni'=> "27764255" ],
        [ 'name'=> "ALICIA YANEL", 'lastname'=> "GONZALEZ BARROS", 'dni'=> "39425803" ],
        [ 'name'=> "ANA ABIGAIL", 'lastname'=> "GUTIERREZ ESQUIBEL", 'dni'=> "39425667" ],
        [ 'name'=> "ANA BEATRIZ", 'lastname'=> "LAURIA", 'dni'=> "37531196" ],
        [ 'name'=> "ANA BELEN", 'lastname'=> "BUSI", 'dni'=> "41727857" ],
        [ 'name'=> "ANA BELEN", 'lastname'=> "RIVEROS", 'dni'=> "42805296" ],
        [ 'name'=> "ANA CANDELA", 'lastname'=> "BRAVO LEONARDELLI", 'dni'=> "41957914" ],
        [ 'name'=> "ANA LAURA", 'lastname'=> "MORENO", 'dni'=> "39955529" ],
        [ 'name'=> "ANA MARIA", 'lastname'=> "PONTORIERO OLMOS", 'dni'=> "33289275" ],
        [ 'name'=> "ANA MILENA", 'lastname'=> "ALMONACI VILLALOBO", 'dni'=> "35852181" ],
        [ 'name'=> "ANA PAULA", 'lastname'=> "MINCONE FLORES", 'dni'=> "39182379" ],
        [ 'name'=> "ANA PAULA", 'lastname'=> "MIRANDA TEJADA", 'dni'=> "43688902" ],
        [ 'name'=> "ANA PAULA", 'lastname'=> "OLIVERA", 'dni'=> "39954224" ],
        [ 'name'=> "ANA PAULA", 'lastname'=> "YORNET MONCHO", 'dni'=> "43489093" ],
        [ 'name'=> "ANA RAQUEL", 'lastname'=> "DIAZ FUNES", 'dni'=> "28040869" ],
        [ 'name'=> "ANA VALENTINA", 'lastname'=> "FLORES", 'dni'=> "41468580" ],
        [ 'name'=> "ANA VALERIA", 'lastname'=> "VEGA", 'dni'=> "29003741" ],
        [ 'name'=> "ANABELLA JANET", 'lastname'=> "AGRELLO CAPUZZELLO", 'dni'=> "46616472" ],
        [ 'name'=> "ANALIA EVANGELINA", 'lastname'=> "PEREYRA TAPIA", 'dni'=> "28539931" ],
        [ 'name'=> "ANALIA MAGALI", 'lastname'=> "MOYANO VILLEGAS", 'dni'=> "42207269" ],
        [ 'name'=> "ANALIA SUSANA", 'lastname'=> "SANTAELLA", 'dni'=> "32007591" ],
        [ 'name'=> "ANDREA ALESSANDRA", 'lastname'=> "ZULIANI LLARENA", 'dni'=> "41957929" ],
        [ 'name'=> "ANDREA ELIZABETH", 'lastname'=> "ALGAÑARAZ", 'dni'=> "38074705" ],
        [ 'name'=> "ANDREA IRIS", 'lastname'=> "LEPEZ", 'dni'=> "38459246" ],
        [ 'name'=> "ANDREA MARIANA", 'lastname'=> "GUZMAN CABALLERO", 'dni'=> "43375926" ],
        [ 'name'=> "ANDREA MICAELA", 'lastname'=> "PELAYES", 'dni'=> "38074757" ],
        [ 'name'=> "ANDREA SOLEDAD", 'lastname'=> "GUTIERREZ", 'dni'=> "40264853" ],
        [ 'name'=> "ANDRES RUBEN", 'lastname'=> "LICCIARDI MELIAN", 'dni'=> "39790601" ],
        [ 'name'=> "ANGELA MILAGROS", 'lastname'=> "GUALLAMA", 'dni'=> "41830896" ],
        [ 'name'=> "ANGELA AYLEN", 'lastname'=> "MOLINA", 'dni'=> "39955011" ],
        [ 'name'=> "ANGELA CAMILA", 'lastname'=> "ACIAR", 'dni'=> "42356627" ],
        [ 'name'=> "ANGELA MAGDALENA", 'lastname'=> "TELLO", 'dni'=> "41468104" ],
        [ 'name'=> "ANGELA ROMINA", 'lastname'=> "POBLETE CASTRO", 'dni'=> "37833024" ],
        [ 'name'=> "ANGELES CAMILA", 'lastname'=> "CASTRO MANSUT", 'dni'=> "42356875" ],
        [ 'name'=> "ANGELICA JOSEFINA", 'lastname'=> "MONARDEZ", 'dni'=> "35735848" ],
        [ 'name'=> "ANGÉLICA ROSA", 'lastname'=> "PORCIGLIO", 'dni'=> "30546509" ],
        [ 'name'=> "ANGELO LEONARDO", 'lastname'=> "CEVALLOS PEREYRA", 'dni'=> "41157166" ],
        [ 'name'=> "ANGIE", 'lastname'=> "LOYOLA", 'dni'=> "42163053" ],
        [ 'name'=> "ANTONELLA", 'lastname'=> "VELARDO", 'dni'=> "41588957" ],
        [ 'name'=> "ANTONELLA DAIANA", 'lastname'=> "MARTINEZ", 'dni'=> "39009098" ],
        [ 'name'=> "ARACELI DEL VALLE", 'lastname'=> "CABALLERO", 'dni'=> "39007808" ],
        [ 'name'=> "ARACELI FLORENCIA", 'lastname'=> "AGILERA", 'dni'=> "39525709" ],
        [ 'name'=> "ARIANA", 'lastname'=> "ERRECALDE YANZON", 'dni'=> "42817152" ],
        [ 'name'=> "ARIANA ROCIO", 'lastname'=> "DIAZ", 'dni'=> "42081122" ],
        [ 'name'=> "AXEL GABRIEL", 'lastname'=> "REINOSO", 'dni'=> "43058469" ],
        [ 'name'=> "AYELEN ALEJANDRA", 'lastname'=> "AROCA", 'dni'=> "35506568" ],
        [ 'name'=> "AYELEN DAIANA", 'lastname'=> "REINOSO", 'dni'=> "40838158" ],
        [ 'name'=> "AYELEN IVON", 'lastname'=> "CALIVAR", 'dni'=> "38078081" ],
        [ 'name'=> "BAHIANA SOL", 'lastname'=> "PLATERO CORREA", 'dni'=> "39011407" ],
        [ 'name'=> "BEATRIZ", 'lastname'=> "RIVERO", 'dni'=> "28668587" ],
        [
          'name'=> "BEATRIZ MARIA DEL CARMEN",
          'lastname'=> "MOLINA NOVARO",
          'dni'=> "36586478",
        ],
        [ 'name'=> "BELEN ANABELLA", 'lastname'=> "SARMIENTO", 'dni'=> "40368849" ],
        [ 'name'=> "BELEN AYELEN", 'lastname'=> "CHACON SORIA", 'dni'=> "42511893" ],
        [ 'name'=> "BELEN DEL ROSARIO", 'lastname'=> "FUENTES", 'dni'=> "33960311" ],
        [ 'name'=> "BETIANA VANESA", 'lastname'=> "CONTRERAS", 'dni'=> "31401537" ],
        [ 'name'=> "BIANCA MARIA LUJAN", 'lastname'=> "MERELES BIANCA", 'dni'=> "41319192" ],
        [ 'name'=> "BLANCA YEMINA", 'lastname'=> "JOFRE", 'dni'=> "35153471" ],
        [ 'name'=> "BRAIAN FEDERICO", 'lastname'=> "VEGA", 'dni'=> "41468156" ],
        [ 'name'=> "BRENDA ARACELI", 'lastname'=> "GALVE MOLINA", 'dni'=> "37521204" ],
        [ 'name'=> "BRENDA GRISEL", 'lastname'=> "MAMONE", 'dni'=> "37742647" ],
        [ 'name'=> "BRISA ARIADNA", 'lastname'=> "CALIVA", 'dni'=> "43489066" ],
        [ 'name'=> "CAMILA", 'lastname'=> "GIMÉNEZ", 'dni'=> "41054792" ],
        [ 'name'=> "CAMILA", 'lastname'=> "GUTIERREZ PREISZ", 'dni'=> "40728729" ],
        [ 'name'=> "CAMILA AGUSTINA", 'lastname'=> "ALANIZ", 'dni'=> "38216883" ],
        [ 'name'=> "CAMILA ALEJANDRA", 'lastname'=> "QUIROGA GOMEZ", 'dni'=> "41830529" ],
        [ 'name'=> "CAMILA MAGALÍ", 'lastname'=> "ECHEVARRIA OYOLA", 'dni'=> "43123291" ],
        [ 'name'=> "CANDELA DEL VALLE", 'lastname'=> "OLIVA", 'dni'=> "43340281" ],
        [ 'name'=> "CANDELA MARYSOL", 'lastname'=> "RIVERO PAEZ", 'dni'=> "39009379" ],
        [ 'name'=> "CANDELA SOFIA", 'lastname'=> "DOMINGUEZ TOBAR", 'dni'=> "42081729" ],
        [ 'name'=> "CANDELA YAZMÍN", 'lastname'=> "VILLAFAÑE", 'dni'=> "43642483" ],
        [ 'name'=> "CAREN DAIANA", 'lastname'=> "ARIAS BONDANZA", 'dni'=> "36252612" ],
        [ 'name'=> "CAREN MICAELA", 'lastname'=> "LUCERO-PEREYRA", 'dni'=> "39792984" ],
        [ 'name'=> "CARINA", 'lastname'=> "FERRER", 'dni'=> "35850906" ],
        [ 'name'=> "CARINA NOEMI", 'lastname'=> "DIAZ", 'dni'=> "26239315" ],
        [ 'name'=> "CARLA", 'lastname'=> "CUELLO", 'dni'=> "43221395" ],
        [ 'name'=> "CARLA GABRIELA", 'lastname'=> "SALINAS LOPEZ", 'dni'=> "39956307" ],
        [ 'name'=> "CARLA LISETTE", 'lastname'=> "MANZANO ALIANTE", 'dni'=> "43952088" ],
        [ 'name'=> "CARLA NOEMÍ", 'lastname'=> "CATALDO DIAZ", 'dni'=> "41776139" ],
        [ 'name'=> "CARLA VANINA ROXANA", 'lastname'=> "AGUILERA CASTRO", 'dni'=> "32140144" ],
        [ 'name'=> "CARLOS HUGO", 'lastname'=> "ESPEJO", 'dni'=> "34864552" ],
        [ 'name'=> "CARLOS MAXIMILIANO", 'lastname'=> "LOVUOLO", 'dni'=> "38463466" ],
        [ 'name'=> "CAROLINA ELIZABETH", 'lastname'=> "PAZ", 'dni'=> "33058571" ],
        [ 'name'=> "CAROLINA MICAELA", 'lastname'=> "ROSALES CORREA", 'dni'=> "43689727" ],
        [ 'name'=> "CATHERINE AYLEN", 'lastname'=> "PEREYRA", 'dni'=> "39792608" ],
        [ 'name'=> "CECILIA ADRIANA", 'lastname'=> "CHAVEZ", 'dni'=> "34657161" ],
        [ 'name'=> "CECILIA ANDREA", 'lastname'=> "JUAREZ SOLER", 'dni'=> "32929495" ],
        [ 'name'=> "CECILIA ELIZABETH", 'lastname'=> "BERON", 'dni'=> "34054472" ],
        [ 'name'=> "CECILIA MARIANA", 'lastname'=> "CABRERA MORENO", 'dni'=> "41221213" ],
        [ 'name'=> "CELENA IVON", 'lastname'=> "SUAREZ", 'dni'=> "37648870" ],
        [ 'name'=> "CELESTE AYELÉN", 'lastname'=> "LUCERO CASTRO", 'dni'=> "42918095" ],
        [ 'name'=> "CELESTE DEL VALLE", 'lastname'=> "GRAMAJO", 'dni'=> "41014289" ],
        [ 'name'=> "CELESTE DEL VALLE", 'lastname'=> "SANCHEZ LUCERO", 'dni'=> "41157050" ],
        [ 'name'=> "CELINA BELEN", 'lastname'=> "BRIZUELA", 'dni'=> "41531314" ],
        [ 'name'=> "CINTHIA ANABEL", 'lastname'=> "ATENCIO", 'dni'=> "35853396" ],
        [ 'name'=> "CINTHIA NOEMI", 'lastname'=> "ILLA ESCUDERO", 'dni'=> "33183896" ],
        [ 'name'=> "CINTHIA PAOLA", 'lastname'=> "MORALES", 'dni'=> "39377158" ],
        [ 'name'=> "CINTHIA ROCIO", 'lastname'=> "CALDERON MORENO", 'dni'=> "38594674" ],
        [ 'name'=> "CINTHYA BEATRIZ", 'lastname'=> "CAPPA GONZALEZ", 'dni'=> "46332115" ],
        [ 'name'=> "CINTIA CELESTE", 'lastname'=> "GONZALEZ", 'dni'=> "38074797" ],
        [ 'name'=> "CINTIA KAREN", 'lastname'=> "OLIVAREZ", 'dni'=> "38591421" ],
        [ 'name'=> "CINTIA LILEN", 'lastname'=> "BRAO REUS", 'dni'=> "39525212" ],
        [ 'name'=> "CINTIA LORENA", 'lastname'=> "BALMACEDA", 'dni'=> "39792617" ],
        [ 'name'=> "CINTIA NOELIA", 'lastname'=> "GARCÍA", 'dni'=> "39994801" ],
        [ 'name'=> "CINTIA NOEMI", 'lastname'=> "CASTRO", 'dni'=> "30091175" ],
        [ 'name'=> "CINTIA ROMINA", 'lastname'=> "RUIZ CORTEZ", 'dni'=> "31510585" ],
        [ 'name'=> "CLARA INÉS", 'lastname'=> "BUSTOS ROCA", 'dni'=> "42516620" ],
        [ 'name'=> "CLAUDIA", 'lastname'=> "GREMOLICHE", 'dni'=> "34245094" ],
        [ 'name'=> "CLAUDIA CECILIA", 'lastname'=> "MONTAÑA GARCIA", 'dni'=> "32140029" ],
        [ 'name'=> "CLAUDIA DANIELA", 'lastname'=> "SOLARES", 'dni'=> "36032437" ],
        [ 'name'=> "CLAUDIA JULIETA", 'lastname'=> "VELIZ CASTRO", 'dni'=> "40368716" ],
        [ 'name'=> "CONSTANZA YAMILA", 'lastname'=> "BALMACEDA", 'dni'=> "43642516" ],
        [ 'name'=> "CRISTIAN RICARDO", 'lastname'=> "DIELE", 'dni'=> "29149040" ],
        [ 'name'=> "CYNTHIA ALEJANDRA", 'lastname'=> "ROMERO", 'dni'=> "32922119" ],
        [ 'name'=> "CYNTHIA IVANNA", 'lastname'=> "MERELES BOLADO", 'dni'=> "33475063" ],
        [ 'name'=> "CYNTHIA LORENA", 'lastname'=> "MÉNDEZ RIVEROS", 'dni'=> "33966590" ],
        [ 'name'=> "CYNTHIA YANINA", 'lastname'=> "IÑON", 'dni'=> "32860086" ],
        [ 'name'=> "DAIANA AILEN DEL MILAGRO", 'lastname'=> "VARGAS", 'dni'=> "38216762" ],
        [ 'name'=> "DAIANA DE LOS ANGELES", 'lastname'=> "SERER CARRIZO", 'dni'=> "39011398" ],
        [ 'name'=> "DAIANA ELISA", 'lastname'=> "VALLES", 'dni'=> "34916757" ],
        [ 'name'=> "DAIANA MARIANELA", 'lastname'=> "LOPEZ", 'dni'=> "40264430" ],
        [ 'name'=> "DAIANA SOLEDAD", 'lastname'=> "SANDANDEZ VARGAS", 'dni'=> "36033142" ],
        [ 'name'=> "DANIELA", 'lastname'=> "PELLICER  LOPEZ", 'dni'=> "40939398" ],
        [ 'name'=> "DANIELA SOLEDAD", 'lastname'=> "ARRANZ", 'dni'=> "38217935" ],
        [ 'name'=> "DANIELA ALEJANDRA", 'lastname'=> "MEDINA ESPEJO", 'dni'=> "37297107" ],
        [ 'name'=> "DANIELA ANDRA", 'lastname'=> "GARRAMUÑO JUÁREZ", 'dni'=> "35505970" ],
        [ 'name'=> "DANIELA ELIZABETH", 'lastname'=> "FIGUEROA", 'dni'=> "36250388" ],
        [ 'name'=> "DARIO ABEL", 'lastname'=> "ANGLADA HERRERA", 'dni'=> "32140159" ],
        [ 'name'=> "DAYANA", 'lastname'=> "COLOMBO", 'dni'=> "40594064" ],
        [ 'name'=> "DAYANA BELEN", 'lastname'=> "VILLAFAÑE", 'dni'=> "37832795" ],
        [ 'name'=> "DAYANA DEL VALLE", 'lastname'=> "FADA RIOS", 'dni'=> "40367815" ],
        [ 'name'=> "DAYANA JUDITH", 'lastname'=> "ROJAS SUAREZ", 'dni'=> "42633085" ],
        [ 'name'=> "DAYANA M.", 'lastname'=> "CHAILE", 'dni'=> "34921144" ],
        [ 'name'=> "DEBORA", 'lastname'=> "CASTRACANI", 'dni'=> "32861088" ],
        [ 'name'=> "DÉVORA CECILIA", 'lastname'=> "FLORES", 'dni'=> "33236916" ],
        [ 'name'=> "DEVORA PAOLA", 'lastname'=> "LUNA FLORES", 'dni'=> "42207045" ],
        [ 'name'=> "DÈVORA YAEL", 'lastname'=> "FERNANDEZ", 'dni'=> "34054946" ],
        [ 'name'=> "EDITH PATRICIA", 'lastname'=> "FERNANDEZ VARGAS", 'dni'=> "17554996" ],
        [ 'name'=> "ELBA DEOLINDA", 'lastname'=> "RAMOS", 'dni'=> "31755106" ],
        [ 'name'=> "ELIA ANTONELLA", 'lastname'=> "SILVA", 'dni'=> "36252450" ],
        [ 'name'=> "ELIANA ABRIL", 'lastname'=> "GALEOTE TAPIA", 'dni'=> "37742769" ],
        [ 'name'=> "ELIANA AYELEN", 'lastname'=> "ARREDONDO", 'dni'=> "40995766" ],
        [ 'name'=> "ELIANA AYELEN", 'lastname'=> "SUAREZ BALMACEDA", 'dni'=> "41468494" ],
        [ 'name'=> "ELIANA CLAUDIA", 'lastname'=> "ZALAZAR GUTIERREZ", 'dni'=> "39011716" ],
        [ 'name'=> "ELIANA ELISABETH", 'lastname'=> "MOLINA DALESIO", 'dni'=> "37506743" ],
        [ 'name'=> "ELIANA EMILCE", 'lastname'=> "MONTAÑA GONZALEZ", 'dni'=> "39182415" ],
        [ 'name'=> "ELIANA GISSELLE", 'lastname'=> "ELIZONDO", 'dni'=> "39548794" ],
        [ 'name'=> "ELIAS", 'lastname'=> "VEGA RETA", 'dni'=> "42852938" ],
        [ 'name'=> "ELIAS DANIEL", 'lastname'=> "RODRIGUEZ BOTELLA", 'dni'=> "36253054" ],
        [ 'name'=> "ELIDA ISABEL", 'lastname'=> "TORRES", 'dni'=> "34190731" ],
        [ 'name'=> "EMELINA SUSANA", 'lastname'=> "LUNA VERA", 'dni'=> "29176391" ],
        [ 'name'=> "EMILIA FERNANDA", 'lastname'=> "FATUN MARIN", 'dni'=> "36032799" ],
        [ 'name'=> "EMILSE VICTORIA", 'lastname'=> "MOLINA FERNANDEZ", 'dni'=> "32808396" ],
        [ 'name'=> "ENZO RUBEN", 'lastname'=> "TOLEDO", 'dni'=> "41776093" ],
        [ 'name'=> "ERICA ALEJANDRA", 'lastname'=> "CALIVA", 'dni'=> "33269248" ],
        [ 'name'=> "ERICA IVANA", 'lastname'=> "ESCALONA", 'dni'=> "34054668" ],
        [ 'name'=> "ERICA JOHANA", 'lastname'=> "MONTAÑO MOYANO", 'dni'=> "34788750" ],
        [ 'name'=> "ERIKA ALEJANDRA", 'lastname'=> "SORIA", 'dni'=> "35506213" ],
        [ 'name'=> "ERIKA ANDREA", 'lastname'=> "VIDELA ELIAS", 'dni'=> "38217607" ],
        [ 'name'=> "ERIKA DIAZ", 'lastname'=> "DIAZ", 'dni'=> "36032673" ],
        [ 'name'=> "ERIKA FABIANA", 'lastname'=> "QUIROGA RODRIGUEZ", 'dni'=> "39011729" ],
        [ 'name'=> "ESTEBAN JOSUE", 'lastname'=> "VIVARES", 'dni'=> "39956282" ],
        [ 'name'=> "ESTEFANIS SOLANGE", 'lastname'=> "ROJAS", 'dni'=> "43376686" ],
        [
          'name'=> "ETEL CAROLINA DEL VALLE",
          'lastname'=> "PORRES TAPIA",
          'dni'=> "31400597",
        ],
        [ 'name'=> "EUGENIA VICTORIA", 'lastname'=> "ROJAS", 'dni'=> "41776371" ],
        [ 'name'=> "EVA JUANA", 'lastname'=> "ONTIVERO DIAZ", 'dni'=> "37924061" ],
        [ 'name'=> "EVELIN DANIELA", 'lastname'=> "CASTRO HEREDIA", 'dni'=> "42334339" ],
        [ 'name'=> "EVELIN ROSANA", 'lastname'=> "LUNA LOPEZ", 'dni'=> "37832687" ],
        [ 'name'=> "EVELYN ALEJANDRA", 'lastname'=> "VARGAS", 'dni'=> "39008854" ],
        [ 'name'=> "EVELYN LUANA", 'lastname'=> "PEÑA OLIVERA", 'dni'=> "42633152" ],
        [ 'name'=> "FABIAN ESTEBAN", 'lastname'=> "CASTRO", 'dni'=> "32624312" ],
        [ 'name'=> "FABIANA ALICIA", 'lastname'=> "GOMEZ CASAS", 'dni'=> "42918267" ],
        [
          'name'=> "FABIANA DE LA MERCED",
          'lastname'=> "BALLESTER  CHAPARRO",
          'dni'=> "43764046",
        ],
        [ 'name'=> "FABIOLA YAEL", 'lastname'=> "PEREIRA ILLANES", 'dni'=> "32761895" ],
        [ 'name'=> "FABRICIO ADRIAN", 'lastname'=> "JORQUERA", 'dni'=> "41774734" ],
        [ 'name'=> "FABRIZIO MIGUEL", 'lastname'=> "YACANTE MUÑOZ", 'dni'=> "41468330" ],
        [ 'name'=> "FACUNDO MARTIN", 'lastname'=> "VEGA", 'dni'=> "41270878" ],
        [ 'name'=> "FACUNDO NICOLAS", 'lastname'=> "LOBOS PELEGRINA", 'dni'=> "42334692" ],
        [ 'name'=> "FACUNDO VALENTIN", 'lastname'=> "QUIROGA", 'dni'=> "43422474" ],
        [ 'name'=> "FANNY ELIZABETH", 'lastname'=> "ARROYO RAMOS", 'dni'=> "31038308" ],
        [ 'name'=> "FATIMA DANIELA", 'lastname'=> "VEGA", 'dni'=> "42452277" ],
        [ 'name'=> "FATIMA MELANIA", 'lastname'=> "VILLAFAÑE ACIAR", 'dni'=> "42334770" ],
        [ 'name'=> "FATIMA ORIANA", 'lastname'=> "QUILPATAY", 'dni'=> "43838309" ],
        [ 'name'=> "FEDERICO ALEJANDRO", 'lastname'=> "RIVERA BRAVO", 'dni'=> "36423913" ],
        [ 'name'=> "FERNANDA", 'lastname'=> "VEGA", 'dni'=> "35505976" ],
        [ 'name'=> "FERNANDA ANABELA", 'lastname'=> "MORALES", 'dni'=> "41122907" ],
        [ 'name'=> "FERNANDA DANIELA", 'lastname'=> "ZAMORA", 'dni'=> "37506942" ],
        [ 'name'=> "FERNANDA DEL ROSARIO", 'lastname'=> "PASTEN", 'dni'=> "40264585" ],
        [ 'name'=> "FERNANDA LUTMILA", 'lastname'=> "AYALA", 'dni'=> "43058957" ],
        [ 'name'=> "FERNANDA MAGALI", 'lastname'=> "RODRIGUEZ", 'dni'=> "39653141" ],
        [ 'name'=> "FERNANDA MÓNICA DANIELA", 'lastname'=> "PEÑA", 'dni'=> "32116624" ],
        [ 'name'=> "FERNANDO ANDRES", 'lastname'=> "DI CARLOS ZATO", 'dni'=> "39525425" ],
        [ 'name'=> "FERNANDO JAVIER", 'lastname'=> "MALLA", 'dni'=> "27682797" ],
        [ 'name'=> "FERNANDO MAXIMILIANO", 'lastname'=> "AGUILERA LEPEZ", 'dni'=> "39183141" ],
        [ 'name'=> "FLORENCIA", 'lastname'=> "MUT CERDERA", 'dni'=> "43376695" ],
        [ 'name'=> "FLORENCIA AGUSTINA", 'lastname'=> "GARCÍA BRUNA", 'dni'=> "42853486" ],
        [ 'name'=> "FLORENCIA AGUSTINA", 'lastname'=> "JALED MORILLA", 'dni'=> "40265190" ],
        [ 'name'=> "FLORENCIA BEATRIZ", 'lastname'=> "VILLAFAÑE PAEZ", 'dni'=> "40591582" ],
        [ 'name'=> "FLORENCIA EMILIA", 'lastname'=> "FERNANDEZ OLIVARES", 'dni'=> "39995313" ],
        [ 'name'=> "FLORENCIA MICAELA", 'lastname'=> "PERALTA", 'dni'=> "42990144" ],
        [ 'name'=> "FLORENCIA SOFIA", 'lastname'=> "MARTIN PUERTA", 'dni'=> "41682501" ],
        [ 'name'=> "FRANCIS EMMANUEL", 'lastname'=> "ARIAS GODOY", 'dni'=> "38074870" ],
        [ 'name'=> "FRANCISCO MATIAS", 'lastname'=> "GAILLEZ LORENZO", 'dni'=> "41957694" ],
        [ 'name'=> "FRANCO EMMANUEL", 'lastname'=> "MORETTI MONTAÑA", 'dni'=> "33759145" ],
        [ 'name'=> "FRANCO EXEQUIEL", 'lastname'=> "SEGURA DIAZ", 'dni'=> "41122748" ],
        [ 'name'=> "FRANCO JAVIER", 'lastname'=> "QUADRI", 'dni'=> "44126583" ],
        [ 'name'=> "GABRIEL ADRIAN", 'lastname'=> "PAREDEZ", 'dni'=> "41054109" ],
        [ 'name'=> "GABRIELA", 'lastname'=> "SAENZ BATISTA", 'dni'=> "37742644" ],
        [ 'name'=> "GABRIELA BELEN", 'lastname'=> "GONZALEZ LUENGO", 'dni'=> "41682788" ],
        [ 'name'=> "GABRIELA BELEN", 'lastname'=> "MONTAÑA", 'dni'=> "33839247" ],
        [ 'name'=> "GABRIELA CAROLINA", 'lastname'=> "GUZMAN SANCHEZ", 'dni'=> "42805703" ],
        [ 'name'=> "GABRIELA GISEL", 'lastname'=> "CASTRO", 'dni'=> "38076286" ],
        [ 'name'=> "GABRIELA JAQUELINA", 'lastname'=> "ARCE", 'dni'=> "28487878" ],
        [ 'name'=> "GABRIELA ROMINA", 'lastname'=> "MURCIANO", 'dni'=> "30891362" ],
        [ 'name'=> "GABRIELA TRINIDAD", 'lastname'=> "SAAVEDRA", 'dni'=> "32088054" ],
        [ 'name'=> "GASPAR ALBERTO", 'lastname'=> "ACOSTA DIAZ", 'dni'=> "31242782" ],
        [ 'name'=> "GENARO", 'lastname'=> "SAAVEDRA", 'dni'=> "18592588" ],
        [ 'name'=> "GEORGINA JAQUEINA", 'lastname'=> "PIZARRO GOMEZ", 'dni'=> "36911538" ],
        [ 'name'=> "GERARDO", 'lastname'=> "TEJADA PEROSA", 'dni'=> "30542854" ],
        [ 'name'=> "GERMAN EZEQUIEL", 'lastname'=> "HERCE PUNAZZO", 'dni'=> "41531565" ],
        [ 'name'=> "GERMAN GABRIEL", 'lastname'=> "CARRION QUIROGA", 'dni'=> "41297188" ],
        [ 'name'=> "GERMAN GABRIEL", 'lastname'=> "MARTINEZ SANCHEZ", 'dni'=> "94326024" ],
        [ 'name'=> "GERMAN GABRIEL", 'lastname'=> "PAEZ PUEBLA", 'dni'=> "39183476" ],
        [ 'name'=> "GIMENA JOSEFINA", 'lastname'=> "ESTRADA", 'dni'=> "39651640" ],
        [ 'name'=> "GIMENA MAGALÍ", 'lastname'=> "PELAYES", 'dni'=> "42163138" ],
        [ 'name'=> "GIMENA SOLEDAD", 'lastname'=> "PEREZ", 'dni'=> "31559680" ],
        [ 'name'=> "GISELA", 'lastname'=> "SANCHEZ", 'dni'=> "32807888" ],
        [ 'name'=> "GISELA BELEN", 'lastname'=> "MONTIVEROS", 'dni'=> "33095245" ],
        [ 'name'=> "GISELA JESÚS", 'lastname'=> "ALVAREZ FARÍAS", 'dni'=> "35849137" ],
        [ 'name'=> "GISELA ROMINA", 'lastname'=> "HEREDIA", 'dni'=> "37005249" ],
        [ 'name'=> "GISELA VANINA", 'lastname'=> "CAMPOS", 'dni'=> "35508336" ],
        [ 'name'=> "GISELLE DEL VALLE", 'lastname'=> "LAHOZ SANCHEZ", 'dni'=> "33759806" ],
        [ 'name'=> "GLADIS SUSANA", 'lastname'=> "GARRIDO GALLARDO", 'dni'=> "24234370" ],
        [ 'name'=> "GLADYS NÉLIDA", 'lastname'=> "PERRAMON DIAZ", 'dni'=> "42235387" ],
        [ 'name'=> "GONZALO FACUNDO", 'lastname'=> "SORIA GOMEZ", 'dni'=> "43556292" ],
        [
          'name'=> "GRACIELA CAROLINA DEL VALLE",
          'lastname'=> "GARCIA PEREZ",
          'dni'=> "37298061",
        ],
        [ 'name'=> "GRISELDA SILVANA", 'lastname'=> "BUSTO", 'dni'=> "29707821" ],
        [ 'name'=> "GUADALUPE", 'lastname'=> "DIAZ", 'dni'=> "40995894" ],
        [ 'name'=> "GUADALUPE", 'lastname'=> "ROBLEDO ANDRADA", 'dni'=> "39792123" ],
        [ 'name'=> "GUSTAVO EZEQUIEL", 'lastname'=> "NUÑEZ DIAZ", 'dni'=> "43157108" ],
        [ 'name'=> "GUSTAVO SANTIAGO", 'lastname'=> "MATTUS GODOY", 'dni'=> "44061304" ],
        [ 'name'=> "HECTOR NAHUEL", 'lastname'=> "FERNANDEZ", 'dni'=> "42207475" ],
        [ 'name'=> "HORACIO AGUSTIN", 'lastname'=> "QUIROGA DIAZ", 'dni'=> "43220873" ],
        [ 'name'=> "IDA VIVIANA", 'lastname'=> "MANCHINI", 'dni'=> "29264215" ],
        [ 'name'=> "IGNACIO ESEQUIEL", 'lastname'=> "LADINO MERCADO", 'dni'=> "39956872" ],
        [ 'name'=> "ILIANA BELINDA NORMA", 'lastname'=> "IBAÑEZ NOGUERA", 'dni'=> "35736929" ],
        [ 'name'=> "INES DEL CARMEN", 'lastname'=> "CAMACHO", 'dni'=> "41054371" ],
        [ 'name'=> "INGRID RITA DAIANA", 'lastname'=> "TRIGO", 'dni'=> "42853431" ],
        [ 'name'=> "ISABEL AMIRA", 'lastname'=> "YANADEL GONZALEZ", 'dni'=> "37297517" ],
        [ 'name'=> "ITATI DEL VALLE", 'lastname'=> "HERNENDEZ MARTINEZ", 'dni'=> "32084330" ],
        [ 'name'=> "IVAN DANIEL", 'lastname'=> "NEIRA", 'dni'=> "38591139" ],
        [ 'name'=> "IVAN JESUS", 'lastname'=> "HERRERA", 'dni'=> "41830562" ],
        [ 'name'=> "IVANA VERÓNICA", 'lastname'=> "ESPINOSA", 'dni'=> "28938799" ],
        [ 'name'=> "IVANNA CAROLINA", 'lastname'=> "GOMEZ CALDERON", 'dni'=> "38614452" ],
        [
          'name'=> "JACQUELINA ELIZABETH",
          'lastname'=> "CAPARROS BUSTOS",
          'dni'=> "43376147",
        ],
        [ 'name'=> "JACQUELINE BELEN", 'lastname'=> "FLORES ORTEGA", 'dni'=> "43280964" ],
        [ 'name'=> "JAIRO IVAN", 'lastname'=> "DIAZ LUNA", 'dni'=> "27764225" ],
        [ 'name'=> "JAQUELINA", 'lastname'=> "GONZALEZ", 'dni'=> "43157472" ],
        [ 'name'=> "JAQUELINE", 'lastname'=> "CATALDO", 'dni'=> "42917870" ],
        [ 'name'=> "JAVIER IVAN", 'lastname'=> "FARIAS AGUERO", 'dni'=> "36254695" ],
        [ 'name'=> "JESICA BELEN", 'lastname'=> "IRAZOQUE MERCADO", 'dni'=> "44018234" ],
        [ 'name'=> "JESICA BELEN", 'lastname'=> "ZALAZAR", 'dni'=> "36250330" ],
        [ 'name'=> "JESICA JOHANA", 'lastname'=> "CRUZ", 'dni'=> "36034807" ],
        [ 'name'=> "JESICA KARIN", 'lastname'=> "MARTIN", 'dni'=> "32007685" ],
        [ 'name'=> "JÉSICA MICAELA", 'lastname'=> "ELIZONDO GÓMEZ", 'dni'=> "42858211" ],
        [ 'name'=> "JESICA SOLEDAD", 'lastname'=> "PEÑA", 'dni'=> "33024846" ],
        [ 'name'=> "JESSICA BELEN", 'lastname'=> "DE LA ROSA", 'dni'=> "39525202" ],
        [ 'name'=> "JESUS SELIM", 'lastname'=> "PELUC  GIMENEZ", 'dni'=> "41641747" ],
        [ 'name'=> "JIMENA", 'lastname'=> "LEALES SANCHEZ", 'dni'=> "43220843" ],
        [ 'name'=> "JIMENA", 'lastname'=> "MERCADO", 'dni'=> "42918487" ],
        [ 'name'=> "JIMENA ALEXANDRA", 'lastname'=> "BARRIO ORTIZ", 'dni'=> "39425837" ],
        [ 'name'=> "JIMENA ALEXANDRA", 'lastname'=> "CASTRO BALMACEDA", 'dni'=> "33743030" ],
        [ 'name'=> "JIMENA BELÉN", 'lastname'=> "MARTINEZ FERRER", 'dni'=> "42633402" ],
        [ 'name'=> "JOANA ERICA", 'lastname'=> "SALINAS", 'dni'=> "35510122" ],
        [ 'name'=> "JOHANA", 'lastname'=> "CARRIZO", 'dni'=> "35511189" ],
        [ 'name'=> "JOHANA DEL CARMEN", 'lastname'=> "LEYES", 'dni'=> "36136419" ],
        [ 'name'=> "JOHANA ADRIANA", 'lastname'=> "RAMOS", 'dni'=> "38216793" ],
        [ 'name'=> "JOHANA DANIELA", 'lastname'=> "ARACENA VIVAREZ", 'dni'=> "35049859" ],
        [ 'name'=> "JOHANA MARIA", 'lastname'=> "TEJADA", 'dni'=> "33759624" ],
        [ 'name'=> "JOHANA S", 'lastname'=> "PAEZ RIOS", 'dni'=> "37924633" ],
        [ 'name'=> "JORGELINA DENISE", 'lastname'=> "GUZMAN", 'dni'=> "35938040" ],
        [ 'name'=> "JOSÉ", 'lastname'=> "ILLANES", 'dni'=> "41958497" ],
        [ 'name'=> "JOSE DANIEL", 'lastname'=> "PERUZZI", 'dni'=> "32374876" ],
        [ 'name'=> "JOSE HERMES", 'lastname'=> "ROSALES", 'dni'=> "17916377" ],
        [ 'name'=> "JOSE LUIS", 'lastname'=> "RODRIGUEZ", 'dni'=> "33759444" ],
        [ 'name'=> "JOSÉ LUIS", 'lastname'=> "MALLEA", 'dni'=> "34459431" ],
        [ 'name'=> "JOSE PASCUAL", 'lastname'=> "VIDELA", 'dni'=> "24270317" ],
        [ 'name'=> "JOSEFINA MARIANELA", 'lastname'=> "RODRIGUEZ FARIAS", 'dni'=> "36544295" ],
        [ 'name'=> "JUAN BAUTISTA", 'lastname'=> "ALOS OLMOS", 'dni'=> "43122532" ],
        [ 'name'=> "JUAN IGNACIO", 'lastname'=> "CONTRERA PERALTA", 'dni'=> "44127765" ],
        [ 'name'=> "JUANA ELENA", 'lastname'=> "GHASTINE", 'dni'=> "43340641" ],
        [ 'name'=> "JULIANA", 'lastname'=> "DIAZ  LEWYLLE", 'dni'=> "44127764" ],
        [ 'name'=> "JULIANA", 'lastname'=> "RIVADEO", 'dni'=> "36384733" ],
        [ 'name'=> "JULIETA AILEN", 'lastname'=> "VERGARA", 'dni'=> "44479906" ],
        [ 'name'=> "JULIETA ANTONELLA", 'lastname'=> "GUEVARA OLIVERA", 'dni'=> "41221271" ],
        [ 'name'=> "JULIETA AYLEN", 'lastname'=> "VEDIA MELVILLE", 'dni'=> "42081622" ],
        [ 'name'=> "JULIETA CAROLINA", 'lastname'=> "ATENCIO", 'dni'=> "35735279" ],
        [ 'name'=> "JULIETA DEL VALLE", 'lastname'=> "ORTIZ ORTIZ", 'dni'=> "36034968" ],
        [ 'name'=> "JULIETA VICTORIA", 'lastname'=> "CARMONA", 'dni'=> "43953033" ],
        [
          'name'=> "JULIO EMILIANO",
          'lastname'=> "FERNANDEZ  VILLAVICENCIO",
          'dni'=> "41830408",
        ],
        [ 'name'=> "KAREN ELIZABETH", 'lastname'=> "AHUMADA PAVON", 'dni'=> "37832736" ],
        [ 'name'=> "KAREN GISELA", 'lastname'=> "BILBAO", 'dni'=> "38590423" ],
        [ 'name'=> "KAREN ROCIO", 'lastname'=> "PALACIO", 'dni'=> "39514739" ],
        [ 'name'=> "KAREN YAMILA", 'lastname'=> "PAEZ", 'dni'=> "42990809" ],
        [ 'name'=> "KARINA DAYANA", 'lastname'=> "MOYA PIZARRO", 'dni'=> "36253599" ],
        [ 'name'=> "KATHERINA DANIELA", 'lastname'=> "DOMINGUEZ ARROYO", 'dni'=> "41598595" ],
        [ 'name'=> "KATHERINA ROXANA SOLEDAD", 'lastname'=> "AVELLANEDA", 'dni'=> "40593976" ],
        [ 'name'=> "KATYA MELINA", 'lastname'=> "FIRMAPAZ CORTEZ", 'dni'=> "38594609" ],
        [ 'name'=> "LAURA BARBARITA", 'lastname'=> "QUIROGA PAEZ", 'dni'=> "31401366" ],
        [ 'name'=> "LAURA BELEN NAHIR", 'lastname'=> "MEDINA TELLO", 'dni'=> "42516796" ],
        [ 'name'=> "LAURA GABRIELA", 'lastname'=> "PALOMO", 'dni'=> "35506085" ],
        [ 'name'=> "LAURA GISEL", 'lastname'=> "FLORES ESPINOSA", 'dni'=> "43058745" ],
        [ 'name'=> "LAURA GISEL", 'lastname'=> "REINOSO", 'dni'=> "37507553" ],
        [ 'name'=> "LAURA NOELIA", 'lastname'=> "USANDIVARES DIAZ", 'dni'=> "28720682" ],
        [ 'name'=> "LAURA SOLEDAD", 'lastname'=> "CASTRO", 'dni'=> "40728040" ],
        [ 'name'=> "LEANDRA EMILCE", 'lastname'=> "BALLESTER", 'dni'=> "35857424" ],
        [ 'name'=> "LEANDRO EMANUEL", 'lastname'=> "LADINO MERCADO", 'dni'=> "38218134" ],
        [ 'name'=> "LEIZA SOLEDAD", 'lastname'=> "RIVERO", 'dni'=> "32817891" ],
        [ 'name'=> "LEÓN ISAIAS", 'lastname'=> "MANCINELLI LLORENS", 'dni'=> "43839370" ],
        [ 'name'=> "LEONARDO RUBEN", 'lastname'=> "SEVILLA QUIROGA", 'dni'=> "33759368" ],
        [ 'name'=> "LEONELA", 'lastname'=> "FERNÁNDEZ", 'dni'=> "34313683" ],
        [ 'name'=> "LEONELA ABIGAIL", 'lastname'=> "BORDON", 'dni'=> "42356352" ],
        [ 'name'=> "LIDIA ELIZABED", 'lastname'=> "RUIZ VALDEVENITES", 'dni'=> "38591196" ],
        [ 'name'=> "LILIANA VANESA", 'lastname'=> "VELAZQUEZ", 'dni'=> "35735763" ],
        [ 'name'=> "LORENA PAOLA", 'lastname'=> "GONZALEZ", 'dni'=> "32878334" ],
        [ 'name'=> "LORENA PAOLA", 'lastname'=> "GUEVARA", 'dni'=> "30052484" ],
        [ 'name'=> "LORENA TAMARA", 'lastname'=> "VARGAS CHAVEZ", 'dni'=> "42249921" ],
        [ 'name'=> "LOURDES BELEN", 'lastname'=> "TEJADA", 'dni'=> "42853497" ],
        [ 'name'=> "LOURDES EUGENIA ZOÉ", 'lastname'=> "RAMOS", 'dni'=> "42356123" ],
        [ 'name'=> "LOURDES MELINA", 'lastname'=> "GUEVARA FERNANDEZ", 'dni'=> "43058972" ],
        [ 'name'=> "LOURDES R", 'lastname'=> "CASTILLO TEJADA", 'dni'=> "42633209" ],
        [ 'name'=> "LOURDES TERESITA", 'lastname'=> "MUÑOZ PEREYRA", 'dni'=> "43642520" ],
        [ 'name'=> "LUANA AYELÉN", 'lastname'=> "QUIROGA GAÑA", 'dni'=> "42516549" ],
        [ 'name'=> "LUCAS ARIEL", 'lastname'=> "GODOY QUEZADA", 'dni'=> "43122502" ],
        [ 'name'=> "LUCAS SEBASTIAN", 'lastname'=> "ROSEL MORALES", 'dni'=> "27849062" ],
        [ 'name'=> "LUCIA BELEN", 'lastname'=> "ANDRADE CONTRERA", 'dni'=> "43952625" ],
        [ 'name'=> "LUCIA BELEN", 'lastname'=> "GUTIERREZ", 'dni'=> "35507480" ],
        [ 'name'=> "LUCÍA MILAGROS", 'lastname'=> "SUARES SALINAS", 'dni'=> "39011381" ],
        [ 'name'=> "LUCIAN AYELEN", 'lastname'=> "AGUERO QUIROGA", 'dni'=> "43489262" ],
        [ 'name'=> "LUCIANA AILEN", 'lastname'=> "GRANADOS BORONAT", 'dni'=> "42334023" ],
        [ 'name'=> "LUCIANA BELEN", 'lastname'=> "LOPEZ LUNA", 'dni'=> "35922324" ],
        [ 'name'=> "LUCIANA BELÉN", 'lastname'=> "ACIAR", 'dni'=> "42081626" ],
        [ 'name'=> "LUCIANA CELESTE", 'lastname'=> "BISSUTTI", 'dni'=> "41809161" ],
        [ 'name'=> "LUCIANA D", 'lastname'=> "MATUS LUCERO", 'dni'=> "38463197" ],
        [ 'name'=> "LUCIANA GABRIELA", 'lastname'=> "MALLA", 'dni'=> "41221365" ],
        [ 'name'=> "LUCIANA VANESSA", 'lastname'=> "CUMPIAN BACA", 'dni'=> "35736545" ],
        [ 'name'=> "LUCILA AYELEN", 'lastname'=> "ESCUDERO GALVAN", 'dni'=> "39377056" ],
        [ 'name'=> "LUDMILA AYLEN", 'lastname'=> "DE LOS RIOS MIRANDA", 'dni'=> "46258672" ],
        [ 'name'=> "LUDMILA IRENE", 'lastname'=> "CASTRO DIAZ", 'dni'=> "43556112" ],
        [ 'name'=> "LUIS", 'lastname'=> "VERA IBAÑEZ", 'dni'=> "43953308" ],
        [ 'name'=> "LUIS JESUS NICOLAS", 'lastname'=> "SANCHEZ CANTO", 'dni'=> "39524850" ],
        [ 'name'=> "LUZ ANTONELLA", 'lastname'=> "FRIAS REYNOSO", 'dni'=> "42711730" ],
        [ 'name'=> "LUZ MARÍA", 'lastname'=> "HURAQUINA", 'dni'=> "42469161" ],
        [ 'name'=> "MACARENA DEL ROSARIO", 'lastname'=> "LUNA CABALLERO", 'dni'=> "39954218" ],
        [ 'name'=> "MAIRA AGOSTINA", 'lastname'=> "CONTRERAS ALVAREZ", 'dni'=> "39524072" ],
        [ 'name'=> "MAIRA ALEJANDRA", 'lastname'=> "RODRIGUEZ", 'dni'=> "38219101" ],
        [ 'name'=> "MAIRA BELEN", 'lastname'=> "SANCHEZ CORDOBA", 'dni'=> "36254303" ],
        [ 'name'=> "MAIRA DAYANA", 'lastname'=> "CORTINEZ  ARROYO", 'dni'=> "36032233" ],
        [ 'name'=> "MAIRA ELIANA", 'lastname'=> "GONZALEZ VERA", 'dni'=> "33364701" ],
        [ 'name'=> "MAIRA JANET", 'lastname'=> "REINOSO NAVEDA", 'dni'=> "40711770" ],
        [ 'name'=> "MAIRA JANET", 'lastname'=> "VARGAS", 'dni'=> "35851050" ],
        [ 'name'=> "MAIRA MICAELA", 'lastname'=> "GARCIA COMELLI", 'dni'=> "35850815" ],
        [ 'name'=> "MAITE LORENA", 'lastname'=> "ROMERO FELICITO", 'dni'=> "28218894" ],
        [ 'name'=> "MALDONADO BUSTOS", 'lastname'=> "ANA LAURA", 'dni'=> "40593688" ],
        [ 'name'=> "MALENA AGOSTINA", 'lastname'=> "TAPIA GUTIERREZ", 'dni'=> "43157436" ],
        [ 'name'=> "MALENA CELINA", 'lastname'=> "CASTILLO SALAVAGIONE", 'dni'=> "41014495" ],
        [ 'name'=> "MARA LUDMILA", 'lastname'=> "PEÑA MASMAN", 'dni'=> "43838872" ],
        [ 'name'=> "MARCELA ANAHI", 'lastname'=> "SORIA GARAY", 'dni'=> "35736072" ],
        [ 'name'=> "MARCELA IVON", 'lastname'=> "FUNES", 'dni'=> "37646566" ],
        [
          'name'=> "MARCOS ESTEBAN JESUS",
          'lastname'=> "FERNANDEZ MARIN",
          'dni'=> "42452441",
        ],
        [ 'name'=> "MARCOS LUIS", 'lastname'=> "NARVAEZ", 'dni'=> "35510756" ],
        [ 'name'=> "MARGARITA", 'lastname'=> "VILLALBA", 'dni'=> "30376751" ],
        [ 'name'=> "MARGOT GISEL", 'lastname'=> "GONZALEZ", 'dni'=> "37297288" ],
        [ 'name'=> "MARIA VICTORIA", 'lastname'=> "MULET  BUSTAMANTE", 'dni'=> "42633094" ],
        [ 'name'=> "MARIA AGOSTINA", 'lastname'=> "DIAZ COSMA", 'dni'=> "34193619" ],
        [ 'name'=> "MARIA AGUSTINA", 'lastname'=> "OLIVEROS FERNANDEZ", 'dni'=> "43376374" ],
        [ 'name'=> "MARIA AGUSTINA", 'lastname'=> "ROMERO-SIREROL", 'dni'=> "41597792" ],
        [ 'name'=> "MARIA AGUSTINA", 'lastname'=> "ROSALES REINOSO", 'dni'=> "40779450" ],
        [ 'name'=> "MARIA ALEJANDRA", 'lastname'=> "CALIVAR ORTIZ", 'dni'=> "28631466" ],
        [ 'name'=> "MARIA ANGELICA", 'lastname'=> "CASTRO", 'dni'=> "33759341" ],
        [ 'name'=> "MARIA ANTONIA", 'lastname'=> "MENDEZ ALVAREZ", 'dni'=> "31098585" ],
        [ 'name'=> "MARIA AYELEN", 'lastname'=> "ORDINES BURGUES", 'dni'=> "41157171" ],
        [ 'name'=> "MARIA AYELEN", 'lastname'=> "UZAIR CORIA", 'dni'=> "39011534" ],
        [ 'name'=> "MARIA BELEN", 'lastname'=> "ILLANES GUEVARA", 'dni'=> "39954625" ],
        [ 'name'=> "MARÍA CECILIA", 'lastname'=> "TURESSO VARGAS", 'dni'=> "41270703" ],
        [ 'name'=> "MARÍA CECILIA", 'lastname'=> "YAÑEZ RODRIGUEZ", 'dni'=> "36252873" ],
        [ 'name'=> "MARIA CELESTE", 'lastname'=> "ACIAR", 'dni'=> "37648890" ],
        [ 'name'=> "MARIA CELESTE", 'lastname'=> "CABALIN", 'dni'=> "38074794" ],
        [ 'name'=> "MARIA CELESTE", 'lastname'=> "CORDOBA DIAZ", 'dni'=> "39525005" ],
        [ 'name'=> "MARIA CELIA", 'lastname'=> "BRIZUELA", 'dni'=> "38074703" ],
        [ 'name'=> "MARIA CELINA", 'lastname'=> "YAÑEZ MORENO", 'dni'=> "42516317" ],
        [ 'name'=> "MARIA CONCEPCIÓN", 'lastname'=> "CORREA PALACIO", 'dni'=> "39183222" ],
        [ 'name'=> "MARIA CRISTINA", 'lastname'=> "SAMPER", 'dni'=> "28475611" ],
        [ 'name'=> "MARIA DE LOS ANGELES", 'lastname'=> "MERCADO", 'dni'=> "42632808" ],
        [ 'name'=> "MARIA DEL PILAR", 'lastname'=> "CARBAJO SUAREZ", 'dni'=> "41830230" ],
        [ 'name'=> "MARIA DEL PILAR", 'lastname'=> "VERGARA ESQUIVEL", 'dni'=> "40470196" ],
        [ 'name'=> "MARIA DOLORES", 'lastname'=> "SAN MARTIN", 'dni'=> "32515661" ],
        [ 'name'=> "MARIA EMILIA", 'lastname'=> "PALOMO", 'dni'=> "43078207" ],
        [ 'name'=> "MARIA ESTHER", 'lastname'=> "AHUMADA PAVON", 'dni'=> "33836831" ],
        [ 'name'=> "MARIA EUGENIA", 'lastname'=> "ARCE CATALDO", 'dni'=> "38078857" ],
        [ 'name'=> "MARIA EUGENIA", 'lastname'=> "FLORES", 'dni'=> "30839391" ],
        [ 'name'=> "MARIA FLORENCIA", 'lastname'=> "MONTENEGRO", 'dni'=> "39424906" ],
        [ 'name'=> "MARIA FLORENCIA", 'lastname'=> "PAEZ PASTOR", 'dni'=> "36033777" ],
        [ 'name'=> "MARÍA GIMENA", 'lastname'=> "MORALES DONOSO", 'dni'=> "38074502" ],
        [ 'name'=> "MARIA GLORIA", 'lastname'=> "DOMINGUEZ", 'dni'=> "34245396" ],
        [ 'name'=> "MARÍA GUADALUPE", 'lastname'=> "HERRERA", 'dni'=> "43689083" ],
        [ 'name'=> "MARÌA INTI", 'lastname'=> "GUZMÀN FERNÀNDEZ", 'dni'=> "41253106" ],
        [ 'name'=> "MARIA ISABEL", 'lastname'=> "BUSTOS", 'dni'=> "32083603" ],
        [ 'name'=> "MARIA JOSE", 'lastname'=> "TELLO", 'dni'=> "40368734" ],
        [ 'name'=> "MARIA JOSE", 'lastname'=> "USAIR", 'dni'=> "34939956" ],
        [ 'name'=> "MARÍA JOSÉ", 'lastname'=> "ESCUDERO PAREDES", 'dni'=> "41270562" ],
        [ 'name'=> "MARIA JULIETA", 'lastname'=> "GARAY", 'dni'=> "35856983" ],
        [ 'name'=> "MARIA JULIETA", 'lastname'=> "LOPEZ RODRIGUEZ", 'dni'=> "37741522" ],
        [ 'name'=> "MARIA LAURA", 'lastname'=> "PARADA", 'dni'=> "40592734" ],
        [ 'name'=> "MARIA LAURA", 'lastname'=> "SIERRA", 'dni'=> "30354675" ],
        [ 'name'=> "MARIA LAURA", 'lastname'=> "TESTA GUZMAN", 'dni'=> "36423412" ],
        [ 'name'=> "MARÍA LAURA", 'lastname'=> "CARRIÓN", 'dni'=> "28538950" ],
        [ 'name'=> "MARIA LAURA.", 'lastname'=> "SAAVEDRA", 'dni'=> "32632990" ],
        [ 'name'=> "MARIA LORENA", 'lastname'=> "SERER MESTRE", 'dni'=> "33429757" ],
        [ 'name'=> "MARIA LOURDES", 'lastname'=> "BONDANZA", 'dni'=> "42853148" ],
        [ 'name'=> "MARIA LOURDES", 'lastname'=> "MONLA MORENO", 'dni'=> "41253183" ],
        [ 'name'=> "MARIA MACARENA", 'lastname'=> "GONZALEZ", 'dni'=> "42516808" ],
        [ 'name'=> "MARIA MILAGROS", 'lastname'=> "CASTRO MANRIQUE", 'dni'=> "40594054" ],
        [ 'name'=> "MARIA MILAGROS", 'lastname'=> "HERRERO PORTILLO", 'dni'=> "43838478" ],
        [ 'name'=> "MARÍA NOELIA", 'lastname'=> "GREGOIRE", 'dni'=> "31643027" ],
        [ 'name'=> "MARIA VALERIA", 'lastname'=> "VALDEZ CUELLO", 'dni'=> "41598681" ],
        [ 'name'=> "MARÍA VERÓNICA", 'lastname'=> "ZALAZAR", 'dni'=> "27350838" ],
        [ 'name'=> "MARIA VICTORIA", 'lastname'=> "BERNAL CORZO", 'dni'=> "42632884" ],
        [ 'name'=> "MARIA VICTORIA", 'lastname'=> "HERRERIA ACIAR", 'dni'=> "38594541" ],
        [ 'name'=> "MARIA VICTORIA", 'lastname'=> "SIREROL", 'dni'=> "39425419" ],
        [ 'name'=> "MARIA VICTORIA", 'lastname'=> "SOSA", 'dni'=> "37437934" ],
        [ 'name'=> "MARIA VICTORIA", 'lastname'=> "VALLEJOS", 'dni'=> "38461310" ],
        [ 'name'=> "MARÍA VICTORIA", 'lastname'=> "TAPIA", 'dni'=> "30872543" ],
        [ 'name'=> "MARIA ZULAYKA", 'lastname'=> "MOREIRA", 'dni'=> "38074876" ],
        [ 'name'=> "MARIANA", 'lastname'=> "BALMACEDA SOLARES", 'dni'=> "42081657" ],
        [ 'name'=> "MARIANA BELEN", 'lastname'=> "MOYANO", 'dni'=> "39376538" ],
        [ 'name'=> "MARIANA BELÉN", 'lastname'=> "DURAN QUIROGA", 'dni'=> "43689034" ],
        [
          'name'=> "MARIANA DE LOS ANGELES",
          'lastname'=> "ACIAR BARRIONUEVO",
          'dni'=> "39954987",
        ],
        [ 'name'=> "MARIANA DEL CARMEN", 'lastname'=> "MALLEA", 'dni'=> "35851213" ],
        [ 'name'=> "MARIANA ELISABETH", 'lastname'=> "LÓPEZ", 'dni'=> "26510218" ],
        [ 'name'=> "MARIANA NOELIA", 'lastname'=> "ZANDON", 'dni'=> "32519489" ],
        [ 'name'=> "MARIANA ROSA", 'lastname'=> "TELLO", 'dni'=> "34697215" ],
        [ 'name'=> "MARIANELA", 'lastname'=> "ROSEL VILCHEZ", 'dni'=> "42081058" ],
        [ 'name'=> "MARIANELA CECILIA", 'lastname'=> "PAEZ MARTINEZ", 'dni'=> "30839322" ],
        [ 'name'=> "MARIÁNGELES", 'lastname'=> "MELIÁN", 'dni'=> "32510559" ],
        [ 'name'=> "MARIANNE ELIANA", 'lastname'=> "CORTINEZ", 'dni'=> "35922280" ],
        [ 'name'=> "MARIANO AGUSTIN", 'lastname'=> "AGUERO SARRACINA", 'dni'=> "41253314" ],
        [ 'name'=> "MARIBEL AYELÉN", 'lastname'=> "FARÍAS -  PUELLES", 'dni'=> "43556662" ],
        [ 'name'=> "MARICEL ALEJANDRA", 'lastname'=> "RUIZ", 'dni'=> "34193584" ],
        [ 'name'=> "MARIELA", 'lastname'=> "RIVAS", 'dni'=> "39224533" ],
        [ 'name'=> "MARIELA SILVINA", 'lastname'=> "AYALA", 'dni'=> "33672463" ],
        [ 'name'=> "MARINA", 'lastname'=> "PIZANO", 'dni'=> "33336260" ],
        [ 'name'=> "MARISA ELIZABETH", 'lastname'=> "GONZALEZ", 'dni'=> "34698092" ],
        [
          'name'=> "MARISEL ALEJANDRA",
          'lastname'=> "HIERREZUELO MORALES",
          'dni'=> "32519504",
        ],
        [ 'name'=> "MARTA AYELEN", 'lastname'=> "ELIZONDO", 'dni'=> "40728382" ],
        [ 'name'=> "MARTIN CARLOS", 'lastname'=> "CASTRO PERALTA", 'dni'=> "32806310" ],
        [ 'name'=> "MARTIN JOSE", 'lastname'=> "LUNA AHUMADA", 'dni'=> "40367812" ],
        [ 'name'=> "MARTINA", 'lastname'=> "SLAVUTZKY ROMERO", 'dni'=> "41598430" ],
        [ 'name'=> "MARTINA NICOLE", 'lastname'=> "MOLINA GONZALEZ", 'dni'=> "43488695" ],
        [ 'name'=> "MATEO", 'lastname'=> "AGÜERO", 'dni'=> "43642266" ],
        [ 'name'=> "MATÍAS GABRIEL", 'lastname'=> "SALVO", 'dni'=> "35411972" ],
        [ 'name'=> "MATIAS NICOLAS", 'lastname'=> "PALMA PAROLI", 'dni'=> "43489305" ],
        [ 'name'=> "MAURICIO ESTEBAN", 'lastname'=> "GONZALEZ", 'dni'=> "40265465" ],
        [ 'name'=> "MAURO GABRIEL", 'lastname'=> "ROCO", 'dni'=> "38590922" ],
        [ 'name'=> "MAXIMILIANO", 'lastname'=> "SANCHEZ", 'dni'=> "43642118" ],
        [ 'name'=> "MAXIMILIANO ANGEL", 'lastname'=> "CORTEZ", 'dni'=> "35735824" ],
        [ 'name'=> "MAYRA", 'lastname'=> "CHAVEZ ZALAZAR", 'dni'=> "29883334" ],
        [ 'name'=> "MAYRA", 'lastname'=> "GONZALEZ ZAPATA", 'dni'=> "37741713" ],
        [ 'name'=> "MAYRA BELEN", 'lastname'=> "GONZALEZ", 'dni'=> "42005695" ],
        [ 'name'=> "MAYRA EDITH", 'lastname'=> "FARIA", 'dni'=> "35852888" ],
        [ 'name'=> "MELANI", 'lastname'=> "DIAZ BALMACEDA", 'dni'=> "39009969" ],
        [ 'name'=> "MELANI AGUSTINA", 'lastname'=> "OLIVARES CABRAL", 'dni'=> "40367691" ],
        [ 'name'=> "MELANI ALEXANDRA", 'lastname'=> "CARRIO BUSTOS", 'dni'=> "39792337" ],
        [ 'name'=> "MELANI ANABEL", 'lastname'=> "CAMARGO", 'dni'=> "36544149" ],
        [ 'name'=> "MELANI ANADELIA", 'lastname'=> "ALBARRACIN", 'dni'=> "35922937" ],
        [ 'name'=> "MÉLANI DANIELA", 'lastname'=> "SANCHEZ", 'dni'=> "38590411" ],
        [ 'name'=> "MELANI ELIANA", 'lastname'=> "VIDELA", 'dni'=> "42990664" ],
        [ 'name'=> "MELANI FLORENCIA", 'lastname'=> "FLORES LIQUITAY", 'dni'=> "42249954" ],
        [ 'name'=> "MELANI GISEL", 'lastname'=> "PONCE LLANOS", 'dni'=> "41054272" ],
        [ 'name'=> "MELANI ROCIO", 'lastname'=> "BALANOVSKY", 'dni'=> "42007708" ],
        [ 'name'=> "MELANIA BEATRIZ", 'lastname'=> "FARIAS", 'dni'=> "34195219" ],
        [ 'name'=> "MELANY MACARENA", 'lastname'=> "RODRIGUEZ VARELA", 'dni'=> "41396219" ],
        [ 'name'=> "MELINA ANABEL", 'lastname'=> "AGUILERA", 'dni'=> "39652526" ],
        [ 'name'=> "MELINA DE LOS ANGELES", 'lastname'=> "ARANCIBIA", 'dni'=> "39792664" ],
        [ 'name'=> "MELINA GABRIELA", 'lastname'=> "GONZALEZ GOMEZ", 'dni'=> "42805120" ],
        [ 'name'=> "MELINA NOEMI", 'lastname'=> "FLORES", 'dni'=> "39994277" ],
        [ 'name'=> "MELISA AYELEN LOURDES", 'lastname'=> "JOFRE MAROTTA", 'dni'=> "41682940" ],
        [ 'name'=> "MELISA DANIELA", 'lastname'=> "RIVEROS", 'dni'=> "37506490" ],
        [ 'name'=> "MELISA JOHANNA", 'lastname'=> "HERRERA", 'dni'=> "32860306" ],
        [ 'name'=> "MELISA MARIA", 'lastname'=> "CORTEZ SANCHEZ", 'dni'=> "32454491" ],
        [ 'name'=> "MELISA MARISOL", 'lastname'=> "SANDOVARES", 'dni'=> "35857141" ],
        [ 'name'=> "MELISA PAULA", 'lastname'=> "QUINTO MACIAS", 'dni'=> "42163887" ],
        [ 'name'=> "MELISA ROCIO", 'lastname'=> "VALDEZ", 'dni'=> "32033867" ],
        [ 'name'=> "MELISA SOLEDAD", 'lastname'=> "FERNANDEZ", 'dni'=> "39182203" ],
        [ 'name'=> "MERCEDES ESTEFANIA", 'lastname'=> "NIEVAS", 'dni'=> "41531828" ],
        [ 'name'=> "MERCEDES VIVIANA", 'lastname'=> "ESTRADA COLLADO", 'dni'=> "37506981" ],
        [ 'name'=> "MICAELA INES", 'lastname'=> "ALCARAZ", 'dni'=> "40258074" ],
        [ 'name'=> "MICAELA ANDREA", 'lastname'=> "PEREYRA CACERES", 'dni'=> "37899411" ],
        [ 'name'=> "MICAELA AYELEN", 'lastname'=> "ECHEGARAY OLIVARES", 'dni'=> "42250258" ],
        [ 'name'=> "MICAELA AYELEN", 'lastname'=> "FERNANDEZ", 'dni'=> "43423351" ],
        [ 'name'=> "MICAELA AYLEN", 'lastname'=> "ARENAS", 'dni'=> "41909212" ],
        [ 'name'=> "MICAELA CARLA AYLÈN", 'lastname'=> "SALGUERO", 'dni'=> "38076293" ],
        [ 'name'=> "MICAELA DAYANA", 'lastname'=> "PAZ-GUILLEN", 'dni'=> "41909168" ],
        [ 'name'=> "MICAELA DEL VALLE", 'lastname'=> "DURAN", 'dni'=> "35857944" ],
        [ 'name'=> "MICAELA ELIANA", 'lastname'=> "SALAS TAPIA", 'dni'=> "36543977" ],
        [ 'name'=> "MICAELA ELIZABETH", 'lastname'=> "FERNANDEZ", 'dni'=> "41253029" ],
        [ 'name'=> "MICAELA J", 'lastname'=> "GAITAN", 'dni'=> "39083401" ],
        [ 'name'=> "MICAELA MABEL", 'lastname'=> "MORALES", 'dni'=> "36032249" ],
        [ 'name'=> "MICAELA NAHIR", 'lastname'=> "ARIAS CARRIZO", 'dni'=> "39011255" ],
        [ 'name'=> "MICAELA SOLEDAD", 'lastname'=> "AUBONE", 'dni'=> "39525328" ],
        [ 'name'=> "MICAELA SOLEDAD", 'lastname'=> "BALMACEDA", 'dni'=> "37742956" ],
        [ 'name'=> "MILAGROS", 'lastname'=> "ABARCA", 'dni'=> "43838229" ],
        [ 'name'=> "MILAGROS DANIELA", 'lastname'=> "ZAMORA", 'dni'=> "42990881" ],
        [ 'name'=> "MILAGROS FABIANA", 'lastname'=> "REINOSO AVILA", 'dni'=> "43488850" ],
        [ 'name'=> "MILAGROS MICAELA", 'lastname'=> "MERCADO GUZMAN", 'dni'=> "42006337" ],
        [ 'name'=> "MIRTA ROSANA", 'lastname'=> "PEREZ", 'dni'=> "22958512" ],
        [ 'name'=> "MONICA", 'lastname'=> "ROJAS", 'dni'=> "32718713" ],
        [ 'name'=> "MONICA ESTER", 'lastname'=> "RODRIGUEZ", 'dni'=> "42516813" ],
        [ 'name'=> "MONICA NOELIA", 'lastname'=> "LEITES JOFRE", 'dni'=> "35922427" ],
        [ 'name'=> "NADIA BELÉN", 'lastname'=> "REYNOSO", 'dni'=> "36678374" ],
        [ 'name'=> "NADIA CAROLINA", 'lastname'=> "CARRIZO", 'dni'=> "27618841" ],
        [ 'name'=> "NADIA FLORENCIA", 'lastname'=> "DALMONEGO", 'dni'=> "38463126" ],
        [ 'name'=> "NADIA JESICA", 'lastname'=> "ALONSO DIAZ", 'dni'=> "32878383" ],
        [ 'name'=> "NADINA TATIANA", 'lastname'=> "CABRERA", 'dni'=> "41054390" ],
        [ 'name'=> "NAHUEL AGUSTIN", 'lastname'=> "VARGAS HERNANDEZ", 'dni'=> "40470618" ],
        [ 'name'=> "NAHUEL ISMAEL", 'lastname'=> "ACIAR PAREDES", 'dni'=> "40728657" ],
        [ 'name'=> "NANCY FABIANA", 'lastname'=> "GAMBOA", 'dni'=> "35735790" ],
        [ 'name'=> "NATALIA ALEJANDRA", 'lastname'=> "TORRES", 'dni'=> "28192527" ],
        [
          'name'=> "NATALIA GLADYS DEL VALLE",
          'lastname'=> "MOLINA NOVARO",
          'dni'=> "40593625",
        ],
        [ 'name'=> "NATALIA SOLEDAD", 'lastname'=> "PALMA MUÑOZ", 'dni'=> "38462439" ],
        [ 'name'=> "NATALIA VANESA", 'lastname'=> "ROSAS MORENO", 'dni'=> "28406627" ],
        [ 'name'=> "NATASHA PRICILA", 'lastname'=> "SORIA", 'dni'=> "41830983" ],
        [ 'name'=> "NAYA MALENA", 'lastname'=> "PEÑA VIDELA", 'dni'=> "44126525" ],
        [ 'name'=> "NÉSTOR GUIDO", 'lastname'=> "SANCHEZ", 'dni'=> "26590440" ],
        [ 'name'=> "NICOLAS", 'lastname'=> "DEUSEDAS", 'dni'=> "43078282" ],
        [ 'name'=> "NICOLAS ALEJANDRO", 'lastname'=> "MOYA GUZMAN", 'dni'=> "44060927" ],
        [ 'name'=> "NICOLAS GERMAN", 'lastname'=> "MARTINEZ", 'dni'=> "38594446" ],
        [ 'name'=> "NICOLE", 'lastname'=> "CUEVA PALACIO", 'dni'=> "43838325" ],
        [ 'name'=> "NICOLE ANDREA", 'lastname'=> "MORENO VERON", 'dni'=> "43689321" ],
        [
          'name'=> "NIKOL DE LOS ANGELES",
          'lastname'=> "SANHUEZA BALLADARES",
          'dni'=> "94546826",
        ],
        [ 'name'=> "NOELIA ANGELICA", 'lastname'=> "CEPEDA ABALLAY", 'dni'=> "31731887" ],
        [ 'name'=> "NOELIA CECILIA", 'lastname'=> "DIAMANTINO", 'dni'=> "35850768" ],
        [ 'name'=> "NOELIA FERNANDA", 'lastname'=> "ZALAZAR DELGADO", 'dni'=> "39995223" ],
        [ 'name'=> "NOELIA MARIA", 'lastname'=> "ROMERO", 'dni'=> "29264168" ],
        [ 'name'=> "NOELIA MARIBEL", 'lastname'=> "ROMERO", 'dni'=> "43489601" ],
        [ 'name'=> "NOELIA NAHIR", 'lastname'=> "ARAYA", 'dni'=> "42081978" ],
        [ 'name'=> "NOELY GISELA", 'lastname'=> "ITURRIETA", 'dni'=> "33743540" ],
        [ 'name'=> "NOEMI ELIZABETH", 'lastname'=> "MICELLI", 'dni'=> "35153445" ],
        [ 'name'=> "NORMA SOFIA", 'lastname'=> "RAMOS", 'dni'=> "40995596" ],
        [ 'name'=> "OLGA EDITH", 'lastname'=> "JOFRE", 'dni'=> "31442159" ],
        [ 'name'=> "ORIANA ALEJANDRA", 'lastname'=> "MORALES RUBIO", 'dni'=> "42633035" ],
        [ 'name'=> "ORLANDO ROMAN", 'lastname'=> "PEREYRA", 'dni'=> "33321586" ],
        [ 'name'=> "ORNELA", 'lastname'=> "PITTALUGA", 'dni'=> "41297301" ],
        [ 'name'=> "OSCAR FABRICIO", 'lastname'=> "ROJAS ZAPPALA", 'dni'=> "32653121" ],
        [ 'name'=> "OSCAR TADEO", 'lastname'=> "TELLO MERLO", 'dni'=> "36423467" ],
        [ 'name'=> "PABLO CESAR", 'lastname'=> "OTIÑANO MEDINA", 'dni'=> "42287895" ],
        [ 'name'=> "PABLO GABRIEL", 'lastname'=> "MERCADO RIVEROS", 'dni'=> "41641831" ],
        [ 'name'=> "PAMELA BEATRIZ", 'lastname'=> "LARA", 'dni'=> "37925346" ],
        [ 'name'=> "PAOLA DEL VALLE", 'lastname'=> "GORDILLO", 'dni'=> "29996770" ],
        [ 'name'=> "PAOLA ELIZABETH", 'lastname'=> "ESPEJO RODRIGUEZ", 'dni'=> "40779015" ],
        [ 'name'=> "PAOLA JOHANNA", 'lastname'=> "GONZALEZ", 'dni'=> "34459760" ],
        [ 'name'=> "PAOLA MICAELA", 'lastname'=> "MAZA SARRACINA", 'dni'=> "38216720" ],
        [ 'name'=> "PAOLA SOLEDAD", 'lastname'=> "ANDUJAR CARBAJAL", 'dni'=> "33355747" ],
        [ 'name'=> "PATRICIA DEL VALLE", 'lastname'=> "BARRIOS", 'dni'=> "22359475" ],
        [ 'name'=> "PATRICIA DEL VALLE", 'lastname'=> "PONCE DIAZ", 'dni'=> "31979608" ],
        [ 'name'=> "PAULA AGUSTINA", 'lastname'=> "ESTRELLA MORENO", 'dni'=> "41776353" ],
        [ 'name'=> "PAULA ANDREA", 'lastname'=> "GARAY", 'dni'=> "21610186" ],
        [ 'name'=> "PAULA EVELYN", 'lastname'=> "ESTESO MERCADO", 'dni'=> "42356223" ],
        [ 'name'=> "PAULA GIMENA", 'lastname'=> "TEJADA", 'dni'=> "35922576" ],
        [ 'name'=> "PAULA MARCELA", 'lastname'=> "OCHOA TEJADA", 'dni'=> "35508539" ],
        [ 'name'=> "PAULA MARILYN", 'lastname'=> "SANCHEZ CABRERA", 'dni'=> "37833271" ],
        [ 'name'=> "PAULA MARTINA", 'lastname'=> "MERCADO", 'dni'=> "41321879" ],
        [ 'name'=> "PAULA VICTORIA", 'lastname'=> "ARANCIBIA BALMACEDA", 'dni'=> "42188069" ],
        [ 'name'=> "PEDRO EMANUEL", 'lastname'=> "SAAVEDRA", 'dni'=> "38461816" ],
        [ 'name'=> "PRISCILA", 'lastname'=> "FLORES", 'dni'=> "39996898" ],
        [ 'name'=> "PRISCILA JAZMIN", 'lastname'=> "ECHEGARAY RODRIGUEZ", 'dni'=> "41468965" ],
        [ 'name'=> "PRISCILA JOHANA", 'lastname'=> "TRONCOSO MANRIQUE", 'dni'=> "37650527" ],
        [ 'name'=> "PRISCILA MAGALI", 'lastname'=> "YORNET VALDEZ", 'dni'=> "40592394" ],
        [ 'name'=> "RAMIRO MARTIN", 'lastname'=> "PUJADO BUSSO", 'dni'=> "40779937" ],
        [ 'name'=> "REGINA DAIANA", 'lastname'=> "VIDELA CARBAJAL", 'dni'=> "41683188" ],
        [ 'name'=> "RICARDO DANIEL", 'lastname'=> "CARRIZO", 'dni'=> "29740288" ],
        [ 'name'=> "ROCIO ABRIL", 'lastname'=> "BAZAN", 'dni'=> "40368780" ],
        [ 'name'=> "ROCÍO AYELÉN", 'lastname'=> "POBLETE-MONGA", 'dni'=> "41774636" ],
        [ 'name'=> "ROCIO BELÉN", 'lastname'=> "LACIAR TELLO", 'dni'=> "40823984" ],
        [ 'name'=> "ROCIO CATALINA", 'lastname'=> "LUNA", 'dni'=> "39650934" ],
        [ 'name'=> "ROCIO DEL CARMEN", 'lastname'=> "ILLANES   QUEVEDO", 'dni'=> "38463911" ],
        [ 'name'=> "ROCIO DEL VALLE", 'lastname'=> "LUCERO ESPEJO", 'dni'=> "39791900" ],
        [ 'name'=> "ROCIO FLORENCIA", 'lastname'=> "AMAYA", 'dni'=> "43489876" ],
        [ 'name'=> "ROCIO JOSEFINA", 'lastname'=> "MARQUEZ PEREYRA", 'dni'=> "44061818" ],
        [ 'name'=> "ROCIO LIHUE", 'lastname'=> "MURCIANO", 'dni'=> "41321567" ],
        [ 'name'=> "ROCIO LUJAN", 'lastname'=> "DIEZ BALMACEDA", 'dni'=> "41641101" ],
        [ 'name'=> "ROCIO MALENA", 'lastname'=> "GONZALEZ DIAZ", 'dni'=> "42451631" ],
        [ 'name'=> "ROCIO MARCELA", 'lastname'=> "GUZMAN", 'dni'=> "41641380" ],
        [ 'name'=> "ROCIO MELISA", 'lastname'=> "DIAZ", 'dni'=> "42516831" ],
        [ 'name'=> "ROCIO MICAELA", 'lastname'=> "ACOSTA", 'dni'=> "40939180" ],
        [ 'name'=> "ROCIO MICAELA", 'lastname'=> "NAVARRO", 'dni'=> "41468216" ],
        [ 'name'=> "ROCIO TRINIDAD", 'lastname'=> "NEIRA", 'dni'=> "42356787" ],
        [ 'name'=> "RODRIGO ALEJANDRO", 'lastname'=> "CARMONA DIPP", 'dni'=> "38592260" ],
        [ 'name'=> "RODRIGO DANIEL", 'lastname'=> "CASTRO ARNAU", 'dni'=> "39425602" ],
        [ 'name'=> "ROMAN ALEJANDRO", 'lastname'=> "DE LA ROSA", 'dni'=> "43763770" ],
        [ 'name'=> "ROMINA AGUSTINA", 'lastname'=> "PEREYRA", 'dni'=> "36768045" ],
        [ 'name'=> "ROMINA ALEJANDRA", 'lastname'=> "ESCUDERO VERGARA", 'dni'=> "29772434" ],
        [ 'name'=> "ROMINA BEATRIZ", 'lastname'=> "GONZALES", 'dni'=> "38074943" ],
        [ 'name'=> "ROMINA BELEN", 'lastname'=> "GATICA PALACIOS", 'dni'=> "34193563" ],
        [ 'name'=> "ROMINA CINTIA", 'lastname'=> "ROJAS", 'dni'=> "39010950" ],
        [ 'name'=> "ROMINA DANIELA", 'lastname'=> "GONZALEZ SARMIENTO", 'dni'=> "37625044" ],
        [ 'name'=> "ROMINA GIMENA", 'lastname'=> "PAEZ PAREDES", 'dni'=> "35849333" ],
        [ 'name'=> "ROMINA GISELA", 'lastname'=> "CASTAÑEDA", 'dni'=> "34427605" ],
        [ 'name'=> "ROMINA MARIBEL", 'lastname'=> "AGUILERA", 'dni'=> "36543878" ],
        [ 'name'=> "ROMINA VALERIA", 'lastname'=> "ROM", 'dni'=> "37005103" ],
        [ 'name'=> "ROSA FLORENCIA", 'lastname'=> "CALIVAR STORNIOLO", 'dni'=> "35735389" ],
        [ 'name'=> "ROSA VALERIA", 'lastname'=> "ARCE", 'dni'=> "36252261" ],
        [ 'name'=> "ROSANA YANETH", 'lastname'=> "VERAGUA RECABARREN", 'dni'=> "34697917" ],
        [ 'name'=> "ROSAURA GABRIELA", 'lastname'=> "IBACETA FERRER", 'dni'=> "37650167" ],
        [
          'name'=> "RUTH FLORENCIA GUADALUPE",
          'lastname'=> "TRIGO ESQUIVEL",
          'dni'=> "43689527",
        ],
        [ 'name'=> "RUTH NOEMI", 'lastname'=> "GALEOTE", 'dni'=> "34697983" ],
        [ 'name'=> "SABRINA AYELEN", 'lastname'=> "CORTEZ MENENDEZ", 'dni'=> "36254447" ],
        [ 'name'=> "SABRINA DESIRE", 'lastname'=> "ACIAR GABRIEL", 'dni'=> "34054385" ],
        [ 'name'=> "SALLY ESTEFANIS", 'lastname'=> "RIOS CORTEZ", 'dni'=> "41830891" ],
        [ 'name'=> "SAMIRA MÉLANI", 'lastname'=> "AVENDAÑO LEYES", 'dni'=> "44061697" ],
        [ 'name'=> "SANDRA", 'lastname'=> "ALAMEDA", 'dni'=> "29888850" ],
        [ 'name'=> "SANDRA AYELEN", 'lastname'=> "RODRIGUEZ", 'dni'=> "39008665" ],
        [ 'name'=> "SANDRA NOEMI", 'lastname'=> "GODOY FUNES", 'dni'=> "35857538" ],
        [ 'name'=> "SANTIAGO TOMÁS", 'lastname'=> "MARQUEZ BILBAO", 'dni'=> "41055424" ],
        [ 'name'=> "SARA MARIANELA", 'lastname'=> "CABRERA", 'dni'=> "44126579" ],
        [ 'name'=> "SEBASTIAN", 'lastname'=> "ARCHILLA", 'dni'=> "40368760" ],
        [ 'name'=> "SEBASTIAN GABRIEL", 'lastname'=> "MARTINEZ SANCHEZ", 'dni'=> "94326022" ],
        [ 'name'=> "SELENE ALDANA", 'lastname'=> "GALEOTE", 'dni'=> "43952053" ],
        [ 'name'=> "SELVA AYELEN", 'lastname'=> "RIVEROS", 'dni'=> "33147012" ],
        [ 'name'=> "SHIRLEY BELEN", 'lastname'=> "CHAVES QUINTANA", 'dni'=> "42711582" ],
        [ 'name'=> "SILVANA ALEJANDRA", 'lastname'=> "CALDERON", 'dni'=> "29174147" ],
        [ 'name'=> "SILVANA GABRIELA", 'lastname'=> "TORRES", 'dni'=> "36251817" ],
        [ 'name'=> "SILVANA LORENA", 'lastname'=> "MORALES CONTRERAS", 'dni'=> "25412372" ],
        [
          'name'=> "SILVIA BEATRIZ DEL VALLE",
          'lastname'=> "VERON FERNANDEZ",
          'dni'=> "34916029",
        ],
        [ 'name'=> "SILVIA JIMENA", 'lastname'=> "ARAYA", 'dni'=> "32351016" ],
        [ 'name'=> "SILVIA MARCELA", 'lastname'=> "CAMPILLAY", 'dni'=> "35736400" ],
        [ 'name'=> "SILVINA RAQUEL", 'lastname'=> "NAVARRO", 'dni'=> "36253609" ],
        [ 'name'=> "SIMON", 'lastname'=> "CARRATÚ", 'dni'=> "39954827" ],
        [ 'name'=> "SOFIA", 'lastname'=> "OCHOA FERNANDEZ", 'dni'=> "44062403" ],
        [ 'name'=> "SOFIA", 'lastname'=> "ROJO", 'dni'=> "39525379" ],
        [ 'name'=> "SOFIA LUJAN", 'lastname'=> "FARIAS  CARDENAS", 'dni'=> "43122560" ],
        [ 'name'=> "SOFIA ALEJANDRA", 'lastname'=> "PALACIOS", 'dni'=> "38480156" ],
        [ 'name'=> "SOFIA ANTONELLA", 'lastname'=> "BERON CHAPARRO", 'dni'=> "43058290" ],
        [ 'name'=> "SOFIA DAYANA", 'lastname'=> "CARRIZO-PERALTA", 'dni'=> "43280618" ],
        [ 'name'=> "SOFIA MACARENA", 'lastname'=> "MORENO MARTIN", 'dni'=> "39009894" ],
        [ 'name'=> "SOFIA MICAELA", 'lastname'=> "BRAVO PASTEN", 'dni'=> "43123182" ],
        [ 'name'=> "SOFIA MILAGROS", 'lastname'=> "FARIAS BECERRA", 'dni'=> "42356242" ],
        [ 'name'=> "SOFIA VANESA", 'lastname'=> "ESCUDERO", 'dni'=> "40369277" ],
        [ 'name'=> "SOLANGE MACARENA", 'lastname'=> "QUIROGA", 'dni'=> "39425712" ],
        [ 'name'=> "SOLANGE MICAELA", 'lastname'=> "RODRIGUEZ OLIVARES", 'dni'=> "41054875" ],
        [ 'name'=> "SOLEDAD CONSTANZA", 'lastname'=> "MARIPAN CASTILLO", 'dni'=> "95380162" ],
        [ 'name'=> "SOLEDAD JULIETA", 'lastname'=> "MENDEZ", 'dni'=> "37005153" ],
        [ 'name'=> "STEFANIA CONCEPCION", 'lastname'=> "SANSONE CORDOBA", 'dni'=> "35506613" ],
        [ 'name'=> "STEFANIA YANEL", 'lastname'=> "FARIA CASTRO", 'dni'=> "39954364" ],
        [ 'name'=> "SUSANA CATALINA", 'lastname'=> "ESPINOZA", 'dni'=> "35188872" ],
        [ 'name'=> "TAMARA BELEN", 'lastname'=> "ARGAÑARAZ DIAZ", 'dni'=> "39956044" ],
        [ 'name'=> "TAMARA MELINA", 'lastname'=> "AMAYA", 'dni'=> "39007514" ],
        [ 'name'=> "TERESA BEATRIZ", 'lastname'=> "BRIZUELA", 'dni'=> "27639420" ],
        [ 'name'=> "VALERIA BELEN", 'lastname'=> "SANCHEZ RODRIGUEZ", 'dni'=> "39956351" ],
        [ 'name'=> "VALERIA LOURDES", 'lastname'=> "VALLES", 'dni'=> "36136358" ],
        [ 'name'=> "VALERIA SOLEDAD", 'lastname'=> "CORTEZ", 'dni'=> "36033932" ],
        [ 'name'=> "VANESA", 'lastname'=> "MONCHO", 'dni'=> "32690087" ],
        [ 'name'=> "VANESA ANDREA", 'lastname'=> "GOMEZ", 'dni'=> "28717843" ],
        [ 'name'=> "VANESA CRISTINA", 'lastname'=> "MADAF OCHOA", 'dni'=> "33475073" ],
        [ 'name'=> "VANESA OLGA", 'lastname'=> "CASTILLO", 'dni'=> "34697758" ],
        [ 'name'=> "VANINA JEANNETTE", 'lastname'=> "NAVEA", 'dni'=> "38461227" ],
        [ 'name'=> "VERONICA ALEJANDRA", 'lastname'=> "ROJAS", 'dni'=> "43122989" ],
        [ 'name'=> "VERONICA PRISCILA", 'lastname'=> "SANCHEZ TORES", 'dni'=> "38463460" ],
        [ 'name'=> "VICTOR ANDRES", 'lastname'=> "GIMENEZ", 'dni'=> "41701163" ],
        [ 'name'=> "VICTORIA BEATRIZ", 'lastname'=> "FERNANDEZ", 'dni'=> "34245113" ],
        [ 'name'=> "VICTORIA DAIANA", 'lastname'=> "FIGUEROA MERCADO", 'dni'=> "43280872" ],
        [ 'name'=> "VICTORIA VANESA", 'lastname'=> "CASTRO ORTIZ", 'dni'=> "34351206" ],
        [ 'name'=> "WALTER", 'lastname'=> "MAZA LEPEZ", 'dni'=> "39525138" ],
        [ 'name'=> "WALTER JOSE", 'lastname'=> "BUSTOS", 'dni'=> "28040403" ],
        [ 'name'=> "WILLIAM OMAR", 'lastname'=> "RODRIGUEZ REINOSO", 'dni'=> "32755892" ],
        [ 'name'=> "YAMILA", 'lastname'=> "CAMAYA", 'dni'=> "40470939" ],
        [ 'name'=> "YAMILA ABIGAIL", 'lastname'=> "GONZALEZ MELIAN", 'dni'=> "45799187" ],
        [ 'name'=> "YAMILA ANDREA", 'lastname'=> "PUTELLI", 'dni'=> "41683082" ],
        [ 'name'=> "YAMILA BEATRIZ", 'lastname'=> "GUALLAMA", 'dni'=> "38219460" ],
        [ 'name'=> "YAMILA GISELLE", 'lastname'=> "ROSAS VIVARES", 'dni'=> "32510452" ],
        [ 'name'=> "YAMILA MARGARITA", 'lastname'=> "DIAZ", 'dni'=> "40728568" ],
        [ 'name'=> "YAMILA ROXANA", 'lastname'=> "ARAOS BORDON", 'dni'=> "37649352" ],
        [ 'name'=> "YAMILA SOLEDAD", 'lastname'=> "GUARDIA SILVA", 'dni'=> "39009589" ],
        [ 'name'=> "YANELA MILAGROS", 'lastname'=> "CRUZ LUNA", 'dni'=> "43838849" ],
        [ 'name'=> "YANELA TAMARA", 'lastname'=> "NAVARRO", 'dni'=> "35924359" ],
        [ 'name'=> "YANET ELIZABETH", 'lastname'=> "IRRAZABAL", 'dni'=> "37004796" ],
        [ 'name'=> "YANINA DEL VALLE", 'lastname'=> "TEJADA GOMEZ", 'dni'=> "37743105" ],
        [ 'name'=> "YANINA GISELLE", 'lastname'=> "LUNA", 'dni'=> "31126000" ],
        [ 'name'=> "YANINA MARILYN", 'lastname'=> "CASTRO", 'dni'=> "39012191" ],
        [ 'name'=> "YAZMIN MICAELA", 'lastname'=> "ELIZONDO", 'dni'=> "42006319" ],
        [ 'name'=> "YESABEL MICAELA", 'lastname'=> "CORSO SANTIVAÑEZ", 'dni'=> "43953117" ],
        [ 'name'=> "YESICA BEATRIZ", 'lastname'=> "RIVAROLA", 'dni'=> "34327729" ],
        [ 'name'=> "YESICA EDITH", 'lastname'=> "GARCIA", 'dni'=> "34255785" ],
        [ 'name'=> "YESICA NATALIA", 'lastname'=> "MARTIN QUINTEROS", 'dni'=> "39652009" ],
        [ 'name'=> "YÉSICA NATALIA", 'lastname'=> "GOMEZ BARRIENTO", 'dni'=> "42616849" ],
        [ 'name'=> "YÉSICA ROMINA", 'lastname'=> "TEJADA", 'dni'=> "39652745" ],
        [ 'name'=> "YESICA YAMIL", 'lastname'=> "CARRIZO AMIN", 'dni'=> "31125589" ],
        [ 'name'=> "YOHANA", 'lastname'=> "REY", 'dni'=> "33525659" ],
        [ 'name'=> "YOHANA ANDREA", 'lastname'=> "ABALLAY PÉREZ", 'dni'=> "39525536" ],
        [ 'name'=> "ZARINA NALÈ", 'lastname'=> "SANCHEZ-ARACENA", 'dni'=> "43838380" ],
      ];

      foreach ($seeds as $seed) {
        Teacher::create([
          $seed

        ]
      );
      }

    }
}
